// // CloudHu:604746493@qq.com All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace GlobalGameplayTags
{
	//Factions
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Factions_ID_Alliance);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Factions_ID_Horde);

	//Input
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Sprint);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Roll);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_MeleeAttack);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_HeavyAttack);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Throw);

}

namespace InventoryGameplayTags
{
	//Inventory.Item.Quality
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Poor);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Uncommon);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Rare);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Epic);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Legendary);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Mythic);

	//Inventory.Item.Equipment
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Type_Sword);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Type_Shield);
}


namespace LocomotionTags
{
	//Global Foley
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Handplant);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Jump);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Land);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Run);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunStrafe);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunBackwds);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Scuff);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffPivot);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffWall);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Tumble);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Walk);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_WalkBackwds);

	//MotionMatching
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Default);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Idle);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Loops);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Pivots);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Starts);
	EPICSQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Stops);
	
}
